set(kconfig_env_dirs)
list(APPEND kconfig_env_dirs ZEPHYR_CMSIS_6_MODULE_DIR=/home/federico/Documents/Zephyr_Intermediate_Course_IOMICO/taskworkspace/deps/modules/hal/cmsis_6)
list(APPEND kconfig_env_dirs ZEPHYR_HAL_STM32_MODULE_DIR=/home/federico/Documents/Zephyr_Intermediate_Course_IOMICO/taskworkspace/deps/modules/hal/stm32)
